### ISSUE TITLE
When there is a try-catch structure in the code, an error will be reported

### ISSUE THREAD

**Issue by HJX-zhanS** [mariusschulz/styx#5]
When there is a try-catch structure in the code, an error will be reported!
# 1. code structure
```
    try {
        window.someNonexistentFunction(); 
    } catch (error) {
        alert('An error happened!');
    }
```

# 2.error
```
Uncaught TypeError: Cannot read property '0' of undefined
d:\nodejs\node_global\node_modules\styx\lib\parser\statements\try.js:5
Debugger attached.
Waiting for the debugger to disconnect...
D:\nodejs\node_global\node_modules\styx\lib\parser\statements\try.js:5
    var handler = tryStatement.handlers[0];
                                       ^

TypeError: Cannot read property '0' of undefined
    at parseTryStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\try.js:5:40)
    at parseStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\statement.js:63:12)
    at Object.parseStatements (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\statement.js:25:26)
    at parseBlockStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\block.js:5:24)
    at Object.parseStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\statement.js:63:12)
    at parseForStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\for.js:39:42)
    at parseStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\statement.js:63:12)
    at Object.parseStatements (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\statement.js:25:26)
    at Object.parseBlockStatement (D:\nodejs\node_global\node_modules\styx\lib\parser\statements\block.js:5:24)
    at parseFunctionDeclaration (D:\nodejs\node_global\node_modules\styx\lib\parser\declarations\function.js:33:30)
Process exited with code 1
```

I need your help, thanks!

**Comment by mariusschulz** [comment]
Hi @HJX-zhanS, I no longer actively maintain this library, I'm afraid.
